
variables:
- template: var.yaml


stages:
    - stage: Build
      displayName: $(env)
      jobs:
      - job : $(env)
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: echo stage name is $(env)


