
variables:
- template: var.yaml


stages:
    - stage: Build
      displayName: $(env)
      jobs:
      - job : linux_agent_job 
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: echo stage name is $(env)


