trigger: none 

parameters:
- name: env
  default: ''

stages:
    - stage: Build
      displayName: $(env)
      jobs:
      - job : $(env)
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: |
              echo my name is $(shiv) 



