trigger: none 


variables:
- template: main.yaml

pool:  
  vmImage: 'ubuntu-latest'  

stages:
- template: stage.yaml # Required as first property. Reference to a template for this stage.
  # parameters:
  #   stage_name: ${{ variables.stage_name }}
  #   dependsonStage: Build
  #   shiv: ${{ variables.shiv }}

# extends:
#    template: "YamlTemplates/Stage/Entrypoint.yaml"  
#    parameters:  
#        RunChangeLogic: 'true'