trigger: none 

pool:  
  vmImage: 'ubuntu-latest'  

variables:
- template: var.yaml

stages:
- template: build.yaml
 
- template: stage.yaml
  parameters:
    stage_name: ${{ variables.stage_dev }}

- template: stage.yaml
  parameters:
    stage_name: ${{ variables.stage_qa }}
    dependsonStage: ${{ variables.dependsonStage }}


# extends:
#    template: "YamlTemplates/Stage/Entrypoint.yaml"  
#    parameters:  
#        RunChangeLogic: 'true'